### ISSUE TITLE
`magisk --install-module /path/to/zip`

### ISSUE THREAD

**Issue by Rwadxvv** [canyie/DreamlandManager#6]
`magisk --install-module /path/to/zip`

_Originally posted by @yujincheng08 in https://github.com/topjohnwu/Magisk/issues/6042#issuecomment-1167209552_

**Comment by Rwadxvv** [comment]
> `magisk --install-module /path/to/zip`
> 
> _Originally posted by @yujincheng08 in https://github.com/topjohnwu/Magisk/issues/6042#issuecomment-1167209552_

**Comment by yujincheng08** [comment]
？
